# Generated by Django 5.2.3 on 2025-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=20, unique=True)),
                ('project_type', models.CharField(choices=[('S&T', 'Science & Technology'), ('R&D', 'Research & Development')], max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('principal_agency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('scheduled_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('pending', 'Pending'), ('up_next', 'up_next')], default='ongoing', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
