# Generated by Django 5.2.3 on 2025-06-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_project_budget_project_budget_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('pending', 'Pending'), ('up_next', 'up_next')], default='ongoing', max_length=10),
        ),
    ]
