# Generated by Django 5.2.3 on 2025-06-20 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_report_report_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'submitted_at', 'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='report_approved',
            field=models.BooleanField(default=False, verbose_name='Report Approved'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_resubmit_requested',
            field=models.BooleanField(default=False, help_text='Admin can request investigator to resubmit report', verbose_name='Resubmission Requested'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Report Submission Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_submitted',
            field=models.BooleanField(default=False, verbose_name='Report Submitted'),
        ),
        migrations.AddField(
            model_name='report',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='submitted', max_length=12),
        ),
        migrations.AlterField(
            model_name='report',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigator_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='dashboard.project'),
        ),
    ]
