# Generated by Django 5.2.3 on 2025-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_approved', 'Report Approved'), ('resubmit_request', 'Resubmission Request'), ('report_rejected', 'Report Rejected')], default='report_approved', max_length=20),
        ),
    ]
