# Generated by Django 5.2.3 on 2025-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_budget_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget Amount'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_unit',
            field=models.CharField(choices=[('', 'Select Unit'), ('rupees', 'Rupees'), ('thousands', 'Thousands'), ('lakhs', 'Lakhs'), ('crores', 'Crores')], default='lakhs', max_length=10, verbose_name='Budget Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('pending', 'Pending'), ('up_next', 'up_next')], default='ongoing', max_length=10),
        ),
    ]
