# Generated by Django 5.2.3 on 2025-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investigator Notification', 'verbose_name_plural': 'Investigator Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_submitted', 'Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('resubmit_request', 'Resubmission Requested')], default='report_submitted', max_length=20),
        ),
    ]
