# Generated by Django 5.2.3 on 2026-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_project_assigned_investigator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'submitted_at', 'ordering': ['-submitted_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Assigned Email'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted'), ('resubmit_requested', 'Resubmit Requested')], default='submitted', max_length=20),
        ),
    ]
