# Generated by Django 5.2.3 on 2026-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_report_options_project_assigned_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guideline_document',
            field=models.FileField(blank=True, null=True, upload_to='guidelines/', verbose_name='Guideline Document'),
        ),
    ]
