# Generated by Django 4.2.7 on 2026-07-16 18:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0021_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ekta_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'md'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('is_indexed', models.BooleanField(default=False)),
                ('chunk_count', models.IntegerField(default=0)),
                ('indexing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='dashboard.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ekta_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supporting Document',
                'verbose_name_plural': 'Supporting Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EktaQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('in_scope', models.BooleanField(default=True)),
                ('sources', models.TextField(blank=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekta_questions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekta_queries', to='dashboard.project')),
            ],
            options={
                'verbose_name': 'Ekta Query Log',
                'verbose_name_plural': 'Ekta Query Logs',
                'ordering': ['-asked_at'],
            },
        ),
    ]
