# Generated by Django 5.2.3 on 2025-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project_budget_amount_project_budget_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='implementing_agencies',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_coordinator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_investigator',
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Completion Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_unit',
            field=models.CharField(choices=[('rupees', 'Rupees'), ('thousands', 'Thousands (₹)'), ('lakhs', 'Lakhs (₹)'), ('crores', 'Crores (₹)')], default='lakhs', max_length=10, verbose_name='Budget Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_agency',
            field=models.CharField(max_length=100, verbose_name='Principal Implementing Agency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('S&T', 'Science & Technology'), ('R&D', 'Research & Development')], default='R&D', max_length=3, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scheduled_completion',
            field=models.DateField(verbose_name='Scheduled Completion Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('pending', 'Pending')], default='ongoing', max_length=10, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
    ]
