"""
Django settings for Drishti project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v++=8s!y8+cv@7ds=-l^12o%v-7^-!+$5jwv-g$#r^7$@41*v='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'dashboard',
    'dashboard.apps.DashboardConfig',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication Settings
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_REDIRECT_URL = 'investigator_dashboard'

# Session Settings
SESSION_COOKIE_AGE = 3600  # 1 hour timeout (good default)
SESSION_SAVE_EVERY_REQUEST = True  # Good for security
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists after browser closes
SESSION_COOKIE_SECURE = True if not DEBUG else False  # HTTPS in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access

# Add these settings at the bottom of your settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ROOT_URLCONF = 'Drishti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.notifications_count'
            ],
        },
    },
]

WSGI_APPLICATION = 'Drishti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'dashboard/static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'  # From your screenshot
EMAIL_PORT = 587                     # TLS port (from screenshot)
EMAIL_USE_TLS = True                 # Required for port 587
EMAIL_HOST_USER = 'apikey'  # Your SMTP login
EMAIL_HOST_PASSWORD = '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'  # Covered in *****
DEFAULT_FROM_EMAIL = 'Drishti App <appdrishty@gmail.com>'  # Customize this

# Application Settings
BASE_URL = 'http://localhost:8000'  # Change to your actual domain
ADMIN_EMAIL = 'appdrishty@gmail.com'



# from django.core.mail import send_mail
# from datetime import datetime

# # Email content
# subject = "Test Email from Django (Plain Text)"
# message = """
# Hello,

# This is a test email sent from Django via Brevo SMTP.

# - Time sent: {time}
# - From: {sender}
# - To: {recipient}

# If you receive this, your email setup is working!

# Best regards,
# Drishti App Team
# """.format(
#     time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#     sender="admdrishti2025@gmail.com",  # Recommended: Use your domain email
#     recipient="pragyesharchit8@gmail.com"  # Actual recipient email
# )

# # Send email
# send_mail(
#     subject=subject,
#     message=message,
#     from_email="admdrishti2025@gmail.com",  # Should match authenticated domain in Brevo
#     recipient_list=["pragyesharchit8@gmail.com"],
#     fail_silently=False,
# )